version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  naologic_app:
    image: loliveira306/naologic_task:1.4
    restart: always
    ports:
      - '3000:3000'
    environment:
      DATABASE_URI: mongodb://root:root@mongodb:27017/naologic?authSource=admin
      DATABASE_NAME: naologic
      GEMINI_API_KEY:
      CSV_FILE_PATH: ./images40.txt
      CRON_TIME: '0 04 * * *'
    depends_on:
      - mongodb
    deploy:
      resources:
        limits:
          memory: 2G
